Repository Makourse/Makourse_BE, pull requests merged in 2025-01, with the labels that each got.

#10 feat: #7 나만의 장소 추가, 삭제, 조회
  makourse/account/models.py
  makourse/course/models.py
  makourse/course/serializers.py
  makourse/course/urls.py
  makourse/course/views.py
Labels: 개발중

#12 feat: #6 세부 일정 보기, 세부 일정 추가, 세부 일정 삭제, 세부 일정수정
  makourse/account/models.py
  makourse/course/admin.py
  makourse/course/models.py
  makourse/course/serializers.py
  makourse/course/urls.py
  makourse/course/views.py
Labels: 통과, 개발완료

#13 feat: #8 모임원 관리
  makourse/account/admin.py
  makourse/account/models.py
  makourse/account/serializers.py
  makourse/account/urls.py
  makourse/account/views.py
  makourse/course/models.py
  makourse/course/serializers.py
  makourse/course/views.py
Labels: 개발중

#16 Feat/#11 소셜로그인 구현
  .gitignore
  makourse/account/admin.py
  makourse/account/models.py
  makourse/account/serializers.py
  makourse/account/urls.py
  makourse/account/views.py
  makourse/course/models.py
  makourse/course/serializers.py
  makourse/course/views.py
  makourse/makourse/settings.py
  makourse/media/user_photo/default.png
  requirements.txt
Labels: 통과, 개발완료

#19 feat/#18 swagger 설정
  makourse/account/urls.py
  makourse/account/views.py
  makourse/course/urls.py
  makourse/course/views.py
  makourse/makourse/settings.py
  makourse/makourse/urls.py
Labels: 개발중

#24 Feat/#14 자동화 배포하기
  .github/workflows/deploy.yml
  makourse/requirements.txt
  requirements.txt
Labels: 개발중

#31 Add: 그룹 멤버 조회시, user 정보 추가
  makourse/account/models.py
  makourse/account/serializers.py
Labels: 통과
